site_name: IndoxRouter
site_description: Documentation for the IndoxRouter Python package
site_author: IndoxRouter Team

theme:
  name: material
  logo: image.png
  favicon: image.png

  palette:
    # Automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer    
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - toc.follow

  font:
    text: Inter
    code: JetBrains Mono

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/osllmai/indoxRouter
      name: IndoxRouter on GitHub
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: Page contents

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage Guide:
      - Basic Usage: usage/basic-usage.md
      - Chat Completions: usage/chat.md
      - Text Completions: usage/completions.md
      - Embeddings: usage/embeddings.md
      - Image Generation: usage/images.md
      - Text-to-Speech: usage/tts.md
      - Response Format: usage/responses.md
      - Usage Tracking: usage/tracking.md
      - Rate Limits: usage/rate-limits.md

  - Examples:
      - Basic Examples: examples/basic.md
      - Advanced Examples: examples/advanced.md
      - OpenAI SDK Usage: examples/openai-sdk.md

  - API Reference:
      - Client Methods: api/client.md
      - Response Schemas: api/responses.md
      - Exceptions: api/exceptions.md

  - Use Cases:
      - Chatbots: use-cases/chatbots.md
      - RAG Systems: use-cases/rag-systems.md
      - Content Generation: use-cases/content-generation.md
      - Document Processing: use-cases/document-processing.md
