name: CI/CD Pipeline for Development Branch for indox router

on:
  push:
    branches: ["development"]

permissions:
  contents: write

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  ######################## Setup Job ########################
  setup:
    uses: ./.github/workflows/setup.yml
    secrets: inherit


  # ######################## Pre-commit Job ########################
  # pre_commit:
  #   needs: setup
  #   name: Linting
  #   uses: ./.github/workflows/lint.yml
  #   secrets: inherit


  # ######################## Lint Job ########################

  # ######################## Tag Job ########################
  # tag_and_release:
  #   needs: [setup , pre_commit]
  #   uses: ./.github/workflows/tag_and_release.yml
  #   secrets: inherit