name: Setup Environment Variables

on:
  workflow_call:
    secrets:
      DISCORD_WEBHOOK_URL:
        required: true


permissions:
  contents: write

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  create-env-file:
    runs-on: [self-hosted, indoxrouterbackend]
    steps:
      - name: Set Variables Based on Branch master
        run: |
          echo "TARGET_FOLDER=${{secrets.TARGET_FOLDER}}" >> $GITHUB_ENV
          echo "COMPOSE_FILE=docker/master/docker-compose.yml" >> $GITHUB_ENV
        #   echo "CONTAINER_NAME=indoxrouter-master" >> $GITHUB_ENV


      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Remove Existing .env File (if exists)
        run: |
          echo "::group::Removing existing .env File"
          ENV_PATH="${{secrets.TARGET_FOLDER}}"
          if [ -f "$ENV_PATH" ]; then
            rm "$ENV_PATH"
            echo "Removed old .env"
          else
            echo ".env does not exist, skipping removal"
          fi
          echo "::endgroup::"




      - name: Create .env in shared folder
        run: |
            # Define the .env file path
            ENV_PATH="${{secrets.TARGET_FOLDER}}"

            # Clear existing .env content (optional, for a fresh start)

            cat << EOF > $ENV_PATH
            #######################################
            #         Application Core            #
            #######################################
            HOST=${{secrets.HOST}}
            PORT=${{secrets.PORT}}
            DEBUG=${{secrets.DEBUG}}


            ################################################################################
            # Discord Configuration
            ################################################################################
            DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}
            EOF

            echo ".env created at $ENV_FILE_PATH"
            cat $ENV_FILE_PATH